# File: .workflow/retrain.yml
name: MLflow CI - Auto Retrain

# KAPAN DIJALANKAN?
on:
  # 1. Saat push ke branch main (UTAMA)
  push:
    branches: [ main ]
  
  # 2. Bisa juga trigger manual dari GitHub
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        default: 'Manual retraining'

# APA YANG DILAKUKAN?
jobs:
  train-model:
    runs-on: ubuntu-latest  # Pakai Ubuntu terbaru
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
   
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # STEP 3: INSTALL MLFLOW
    - name: Install MLflow
      run: |
        pip install mlflow
        pip install pandas scikit-learn  # Dependencies dasar
    
    # STEP 4: JALANKAN TRAINING
    - name: Run MLflow Project
      run: |
        cd MLProject
        echo "ðŸš€ Starting MLflow training..."
        mlflow run . --env-manager=local
        echo "âœ… Training completed!"
    
    # STEP 5: SIMPAN HASIL (OPSIONAL)
    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-results
        path: MLProject/mlruns/
        retention-days: 7
